definitions:
  model.Todo:
    properties:
      completed_time:
        description: 完成时间
        type: string
      created_at:
        description: 创建时间（由GORM自动管理）
        type: string
      id:
        description: 主键ID
        type: integer
      task_type:
        description: 任务类型
        type: integer
      title:
        description: DeletedAt     gorm.DeletedAt `gorm:"index"`
        type: string
      updated_at:
        description: 最后一次更新时间（由GORM自动管理）
        type: string
    type: object
info:
  contact: {}
  description: Go 语言编程之旅：一起用 Go 做项目
  termsOfService: https://github.com/go-programming-tour-book
  title: 博客系统
  version: "1.0"
paths:
  /api/v1/Todo/{id}:
    put:
      parameters:
      - description: 标签ID
        in: body
        name: tag_id
        schema:
          type: string
      - description: 文章标题
        in: body
        name: title
        schema:
          type: string
      - description: 文章简述
        in: body
        name: desc
        schema:
          type: string
      - description: 封面图片地址
        in: body
        name: cover_image_url
        schema:
          type: string
      - description: 文章内容
        in: body
        name: content
        schema:
          type: string
      - description: 修改者
        in: body
        name: modified_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Todo'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 更新文章
swagger: "2.0"
